### ISSUE TITLE
Traceback  Error

### ISSUE THREAD

**Issue by mtstomy** [Carapacik/cambridge-dictionary-scraper#2]
I get this error :
`Traceback (most recent call last):
  File "C:\Users\TOMY\Desktop\cambridge-dictionary-scraper-main\get_all_words.py", line 83, in <module>
    for wordBegin in data1:
NameError: name 'data1' is not defined`

**Comment by Carapacik** [comment]
There may be 2 reasons for this:

1. Cambridge dictionary has put protection on selenium-stealth
2. selenium has been updated to version 4
